# Generated by Django 4.2.1 on 2023-12-18 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_learning_prerequisite_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='learning',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='learning',
            name='description',
            field=models.CharField(default='Course Property Description', max_length=20),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='prerequisite',
            name='description',
            field=models.CharField(default='Course Property Description', max_length=20),
        ),
        migrations.AddField(
            model_name='tag',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(default='Course Property Description', max_length=20),
        ),
    ]
