# Generated by Django 4.2.1 on 2023-12-18 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_preview',
            field=models.BooleanField(default=False),
        ),
    ]
