# Generated by Django 4.2.1 on 2023-12-18 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_alter_course_description_alter_course_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
